### ISSUE TITLE
Changing the feature handling to be more like the official Icinga2 way?

### ISSUE THREAD

**Issue by NeverUsedID** [Icinga/ansible-icinga2#47]
Hi there,

what do you all think about changing the behavior of i2_custom_features to use the feature-available folder instead of the features-enabled folders and use the original icinga command "icinga2 feature enable/disable" to manage the features?

Changes needed:

### i2_custom_features
- [ ] i2_custom_features need to create new feature configs inside features-available instead of features enabled.
- [ ] Maybe rename i2_custom_features to i2_create_features

I would add another variable to make it possible to name the config file other then the feature. F.e. name the file for the ApiListener "api" too.

### i2_features

- [ ] i2_features need to use the icinga command to enable/disable commands instead of deleting them, directly in the folder.
- [ ] i2_feature need to get config option like i2_custom_feature, but instead of replacing the feature like i2_custom_features will do, it will regex replace lines in the exiting configs.
- [ ]  Add "enabled: true/false" as config variable
- [ ] Maybe renaming i2_features to i2_manage_features 

Maybe add a "disable_none_managed: true" variable to remove all conf files in features-enabled before configuring. Still not sure, how to do that without doing it on every run.

### Example:

```
i2_manage_features:
  disable_none_managed: "true"
  api: 
    enable: true 
    config: 
      accept_commands: "true"
  notifications:  
    enable: false 
```
